spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tpD3ZR%w3s23T
    url: jdbc:mysql://localhost:3306/iqwddbv3?&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  main:
    web-application-type: none
  sql:
    init:
      mode: always